/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// This file reads Supabase connection info from Vite env variables when available.
// Set the following in your local .env files (do NOT commit secrets):
// VITE_SUPABASE_URL=https://<project-ref>.supabase.co
// VITE_SUPABASE_PROJECT_ID=<project-ref>
// VITE_SUPABASE_ANON_KEY=<anon/public-key>

// Safely read environment variables for both browser (Vite) and Node environments.
// Direct approach since we're in a .tsx file that should only run in Vite/browser context
let _env: any = {};
try {
  // Check if we're in a browser/Vite environment that supports import.meta
  if (typeof window !== 'undefined' && typeof import.meta !== 'undefined') {
    _env = (import.meta as any).env || {};
  } else if (typeof process !== 'undefined' && process?.env) {
    // Fallback to process.env for server-side or Node contexts
    _env = process.env;
  }
} catch (e) {
  // If all else fails, try process.env
  _env = (typeof process !== 'undefined' && process?.env) || {};
}// Prefer explicit VITE_SUPABASE_PROJECT_ID, then derive from VITE_SUPABASE_URL if provided, else fall back to hard-coded ref.
function deriveProjectIdFromUrl(url?: string) {
	if (!url) return undefined;
	try {
		const u = new URL(url);
		const host = u.hostname; // e.g. hmjlivtxnwyitogquflp.supabase.co
		const parts = host.split('.');
		return parts.length ? parts[0] : undefined;
	} catch (e) {
		return undefined;
	}
}

export const projectId = _env.VITE_SUPABASE_PROJECT_ID ?? deriveProjectIdFromUrl(_env.VITE_SUPABASE_URL) ?? "zypsbvzpbypsaazinoqe";
export const publicAnonKey = _env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cHNidnpwYnlwc2Fhemlub3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NzA5MTYsImV4cCI6MjA3ODM0NjkxNn0.OO4yCx0Nr6vXIay0IS9HR_UApLcU-zVQSCXhCAwuqd0";

// Optional: export full URL if VITE_SUPABASE_URL provided
export const supabaseUrl = _env.VITE_SUPABASE_URL ?? `https://${projectId}.supabase.co`;