/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hmjlivtxnwyitogquflp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtamxpdnR4bnd5aXRvZ3F1ZmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMzU5MTIsImV4cCI6MjA3NzcxMTkxMn0.msPlKrV6X7g-o-So2rudIJR78LlmSfYjpk09hzEMGz4"